name: Run unit tests on client
on:
  pull_request:
    types: [opened, reopened, ready_for_review, edited, synchronize]

jobs:
  build:
    name: Run Tests on client
    runs-on: ubuntu-latest
    environment: production
    permissions:
      pull-requests: write
      actions: read
      checks: read
      contents: read
      deployments: read
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: npm install
        run: npm install
        working-directory: ./client

      - name: Check Unit Tests
        run: npm test
        working-directory: ./client
